from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        """
        Meta class for OrderForm to specify model and fields.
        """
        model = Order
        # List the fields from the Order model that the user should fill in
        fields = (
            'full_name', 'email', 'phone_number',
            'street_address1', 'street_address2',
            'town_or_city', 'postcode', 'county',
            'country',
        )

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field.
        """
        super().__init__(*args, **kwargs) # Call the default __init__ first

        # Define placeholders for the form fields
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'postcode': 'Postal Code',
            'town_or_city': 'Town or City',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2 (Optional)',
            'county': 'County, State or Locality (Optional)',
        }

        # Set autofocus attribute on the first field for better UX
        self.fields['full_name'].widget.attrs['autofocus'] = True

        # Iterate through the form fields to apply customizations
        for field_name, field in self.fields.items():
            # Add '*' to placeholder for required fields
            if field.required:
                # Ensure the field name exists in placeholders before formatting
                if field_name in placeholders:
                     placeholder = f'{placeholders[field_name]} *'
                else:
                    # Fallback if no placeholder defined (e.g., for country)
                    placeholder = field.label if field.label else field_name.replace('_', ' ').title() + ' *'

            # Set the placeholder attribute if defined
            if field_name in placeholders:
                if not field.required:
                    placeholder = placeholders[field_name]
                field.widget.attrs['placeholder'] = placeholder

            field.widget.attrs['class'] = 'stripe-style-input'

            # Remove the default form field labels generated by Django
            field.label = False