# Generated by Django 5.2 on 2025-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_friendly_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Display this on the homepage bestseller section?'),
        ),
    ]
